adjective1 = input("what is adjective1?\n")
noun1 = input("what is noun1?\n")
adjective2 = input("adjective2?\n")
noun2 = input("what is noun2?\n")
adjective3 = input("what is adjective3\n")
adjective4 = input("what is adjective4\n")
noun3 = input("what is noun3\n")
adjective5 = input("what is adjective5\n")
adjective6 = input("what is adjective6\n")
pluralnoun = input("what is pluralnoun\n")

print ("Star Wars is a " + adjective1 + " " + noun1 + " of " + adjective2 + " versus evil in a " + noun2 + " far far away. There are " + adjective3 + " battles between " + adjective4 + " " + noun3 + " in " + adjective5 + " space and " + adjective6 + " duels with " + pluralnoun)